### ISSUE TITLE
Unable to import `require('mock-socket')`

### ISSUE THREAD

**Issue by benedictchen** [thoov/mock-socket#59]
`require('mock-socket')`

> require('mock-socket')

{}

> require('mock-socket').MockServer

undefined

> var MockServer = require('mock-socket')

undefined

> MockServer

{}

> var server = new MockServer()

TypeError: MockServer is not a function
    at repl:1:14
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
    at REPLServer.Interface._ttyWrite (readline.js:826:14)
>

**Comment by thoov** [comment]
This is now supported. check the readme
