### ISSUE TITLE
Error: Could not find module `mock-socket` imported from `(require)`

### ISSUE THREAD

**Issue by badazz91** [thoov/mock-socket#73]
Just tried to use this lib in my ember-test environment. I simply installed it with npm.

Importing it like this: 

```
var mockWebSocket = require('mock-socket').WebSocket;
var mockServer = require('mock-socket').Server;
 ```

Or like this:

```
import { WebSocket, Server } from 'mock-socket';
```

Results in the same error:

```
Error: Could not find module `mock-socket` imported from `(require)`
    at missingModule (http://localhost:4201/assets/vendor.js:173:11)
    at findModule (http://localhost:4201/assets/vendor.js:188:17)
    at requireModule (http://localhost:4201/assets/vendor.js:177:12)
    at Module.callback (http://localhost:4201/assets/tests.js:406:23)
    at Module.exports (http://localhost:4201/assets/vendor.js:92:34)
    at Module.build (http://localhost:4201/assets/vendor.js:142:10)
    at findModule (http://localhost:4201/assets/vendor.js:190:9)
    at requireModule (http://localhost:4201/assets/vendor.js:177:12)
    at Object.TestLoader.require (http://localhost:4201/assets/test-loader.js:67:9)
    at Object.TestLoader.loadModules (http://localhost:4201/assets/test-loader.js:58:18)
```

Am I doing something wrong?

**Comment by thoov** [comment]
@badazz91 If you are using it within ember then you will need to install it via bower. 

```
bower install mock-socket
```

Then in your ember-cli-build.js add:

https://github.com/thoov/ember-websockets/blob/master/ember-cli-build.js#L17

Let me know if this works for you.

**Comment by badazz91** [comment]
No luck so far. Installed it via bower and included it in the ember-cli-build.js like this:

```
  app.import('bower_components/mock-socket/dist/mock-socket.min.js', {
    exports: {
      'mock-socket': [
        'default',
        'WebSocket',
        'Server'
      ]
    }
  });
```

Yet the import in my test file stil fails... Am I missing something?

**Comment by badazz91** [comment]
If included in the ```ember-cli-build.js``` you can simply access it like this:

```
 window.MockServer
 window.MockWebSocket
 window.MockSocketIO
```

Sorry for not reading the documentation more thoroughly ;-)

**Comment by thoov** [comment]
@badazz91 Glad you were able to get it installed!
